#!/bin/bash
# Bootstrap script for Workspace setup

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$SCRIPT_DIR"
CLAUDE_DIR="$HOME/.claude"

echo "🏗️  Bootstrapping Workspace..."

# Ensure Claude directories exist
mkdir -p "$CLAUDE_DIR/commands"

# Store workspace paths for global commands
echo "→ Configuring workspace paths"
WIKI_DIR="$HOME/projects/team-wiki"
cat > "$CLAUDE_DIR/workspace-path.txt" << EOF
WORKSPACE_DIR=$WORKSPACE_DIR
WORKSPACE_DATA_DIR=$WORKSPACE_DIR/workspace-data
WIKI_DIR=$WIKI_DIR
EOF
echo "  ✓ Workspace paths stored:"
echo "    Framework: $WORKSPACE_DIR"
echo "    Data: $WORKSPACE_DIR/workspace-data"
echo "    Wiki: $WIKI_DIR"

# Copy global commands
echo "→ Installing global commands"
if [ -d "$WORKSPACE_DIR/commands" ]; then
    cp "$WORKSPACE_DIR/commands"/*.md "$CLAUDE_DIR/commands/" 2>/dev/null || true
    COMMAND_COUNT=$(ls -1 "$WORKSPACE_DIR/commands"/*.md 2>/dev/null | wc -l | tr -d ' ')
    echo "  ✓ $COMMAND_COUNT commands installed globally (task, visual, wiki)"
else
    echo "  ⚠️  No commands directory found"
fi

# Setup workspace-data
echo "→ Setting up workspace-data"
if [ ! -d "$WORKSPACE_DIR/workspace-data" ]; then
    # Prompt for workspace-data repo URL
    echo "  Enter workspace-data repository URL (or press Enter to create locally):"
    read -r DATA_REPO_URL

    if [ -n "$DATA_REPO_URL" ]; then
        echo "  Cloning workspace-data from: $DATA_REPO_URL"
        git clone "$DATA_REPO_URL" "$WORKSPACE_DIR/workspace-data"
        echo "  ✓ workspace-data cloned"
    else
        echo "  Creating local workspace-data repository"
        mkdir -p "$WORKSPACE_DIR/workspace-data"
        cd "$WORKSPACE_DIR/workspace-data"
        git init
        echo "  ✓ Local workspace-data repo initialized"
    fi
else
    echo "  ✓ workspace-data already exists"
fi

# Create necessary data directories in workspace-data
mkdir -p "$WORKSPACE_DIR/workspace-data/active"
mkdir -p "$WORKSPACE_DIR/workspace-data/weeks"

# Create initial dashboard.md if it doesn't exist
if [ ! -f "$WORKSPACE_DIR/workspace-data/dashboard.md" ]; then
    cat > "$WORKSPACE_DIR/workspace-data/dashboard.md" << 'EOF'
# Workspace

> Last updated: —

## Active Tasks

No active tasks. Create one with `/task create`.

## This Week
- Completed: 0 tasks
- In progress: 0 tasks
EOF
fi

# Setup wiki-data
echo "→ Setting up wiki knowledge base"
if [ ! -d "$WIKI_DIR" ]; then
    echo "  Creating wiki directory at $WIKI_DIR"
    mkdir -p "$WIKI_DIR"
    mkdir -p "$WIKI_DIR/how-to"
    mkdir -p "$WIKI_DIR/architecture"
    mkdir -p "$WIKI_DIR/troubleshooting"
    mkdir -p "$WIKI_DIR/onboarding"
    mkdir -p "$WIKI_DIR/reference"
    mkdir -p "$WIKI_DIR/uncategorized"
    echo "  ✓ Wiki directory created with category folders"
else
    # Ensure all category folders exist
    mkdir -p "$WIKI_DIR/how-to"
    mkdir -p "$WIKI_DIR/architecture"
    mkdir -p "$WIKI_DIR/troubleshooting"
    mkdir -p "$WIKI_DIR/onboarding"
    mkdir -p "$WIKI_DIR/reference"
    mkdir -p "$WIKI_DIR/uncategorized"
    echo "  ✓ Wiki directory already exists"
fi

# Create initial wiki-index.md if it doesn't exist
if [ ! -f "$WIKI_DIR/wiki-index.md" ]; then
    cat > "$WIKI_DIR/wiki-index.md" << 'EOF'
# Wiki Index

> Last updated: —
> Total articles: 0 | Published: 0 | Drafts: 0

## How-To Guides
(empty)

## Architecture
(empty)

## Troubleshooting
(empty)

## Onboarding
(empty)

## Reference
(empty)

## Uncategorized
(empty)

---
*Regenerated by `/wiki review`. Browse in Obsidian for best experience.*
EOF
    echo "  ✓ Initial wiki-index.md created"
fi

# Make scripts executable
chmod +x "$WORKSPACE_DIR/scripts"/*.sh

echo ""
echo "✅ Bootstrap complete!"
echo ""
echo "Next steps:"
echo "1. Use '/task review' from anywhere to get started"
echo "2. Try: /task create \"Test the system\" high priority"
echo "3. Sync data: cd workspace-data && git remote add origin <your-private-repo>"
echo ""
echo "Available commands:"
echo "- /task    - Unified task & workspace management"
echo "- /wiki    - Knowledge base & documentation"
echo "- /visual  - Real-time dashboard visualization"
echo ""
echo "Utilities:"
echo "- ./scripts/sync.sh - Sync both framework and data repos"
echo ""
echo "Data location: $WORKSPACE_DIR/workspace-data/"
echo "Wiki location: $WIKI_DIR/"
echo ""
